### ISSUE TITLE
Create Win32 MingGW build

### ISSUE THREAD

**Issue by stalkerg** [stalkerg/postgres_cmake#10]

**Comment by x4m** [comment]
Please consider creating Windows build on VM. It would be cool to just download VM stuffed with all things ready to hack.

I can create Windows VM in Azure from my university account, if you like. We will just skip windows activation, and then we can distribute VM image...I think so, never read eula...

**Comment by stalkerg** [comment]
> Please consider creating Windows build on VM. It would be cool to just download VM stuffed with all things ready to hack.

Interesting idea. Can you make separate issue?

**Comment by stalkerg** [comment]
We have here a big difference between MinGW and MSYS/Cygwin. Some work done for MSYS gcc.

**Comment by stalkerg** [comment]
MinGW/Msys done.
