### ISSUE TITLE
Build VM for Windows

### ISSUE THREAD

**Issue by x4m** [stalkerg/postgres_cmake#21]
Please consider VM for windows build.
Currently Postgres build for windows is painful due to manual dependancies resolution.
You have to install apropriate MSVS, SDK, bison, flex, python, perl, etc etc.
Btw, in my expirience, bison and flex from MinGW won't do the trick. May be I'm just not lucky enough.

It would be wonderfull if you could start hacking just by downloading unactivated windows VM stuffed with free IDE (VC 2015 Community or we can try asking JetBrains for CLion) or without IDE at all.

If you wish I can provide you with Azure Hyper-V machine from my teacher MSDN Subscription from Ural Federal University.

**Comment by stalkerg** [comment]
It will be nice. But I don't know when I can do it.

**Comment by x4m** [comment]
Just ping me when you will have some time, I'll start VM and give you ip
and creds for rdp.

2016-06-30 16:45 GMT+05:00 Yury Zhuravlev notifications@github.com:
