### ISSUE TITLE
Failure on OSX with OpenSSL

### ISSUE THREAD

**Issue by michaelpq** [stalkerg/postgres_cmake#24]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSL_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/mpaquier/git/postgres/src/interfaces/libpq
   used as include directory in directory /Users/mpaquier/git/postgres/contrib/pgcrypto

FWIW, I am using OpenSSL from brew, but I did not link to it using the first command of cmake in README.md.

**Comment by stalkerg** [comment]
1. I fix errors if OpenSSL not found.
2. You can use -DOPENSSL_ROOT_DIR for help CMake. 

MacOSX I tested without brew or ports. I will try fix it today.

**Comment by stalkerg** [comment]
Can you try again with -DOPENSSL_ROOT_DIR ? 

PS System OpenSSL works correctly on 2 own Macs.

**Comment by stalkerg** [comment]
Close.
